server:
  port: 11200
spring:
  application:
    name: api-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer2:6871/eureka/,http://root:123456@peer2:6872/eureka/,http://root:123456@peer3:6873/eureka/
