server:
  port: 11201
spring:
  application:
    name: api-consumer

management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://root:123456@peer2:6871/eureka/,http://root:123456@peer2:6872/eureka/
