spring:
  application:
    name: api-gateway
server:
  port: 10120


zuul:
  routes:
    api-a.path: /api/**
    api-a.serviceId: api-integration
eureka:
  client:
    service-url:
       defaultZone: http://root:123456@peer2:6871/eureka/,http://root:123456@peer2:6872/eureka/,http://root:123456@peer3:6873/eureka/


