spring:
  application:
    name: api-gateway
server:
  port: 10120


zuul:
  routes:
    api-a.path: /api/**
    api-a.serviceId: api-integration
eureka:
  client:
    service-url:
       defaultZone: http://localhost:1110/eureka/


